#! /bin/bash

rm src/table-of-styles.mdx
cat src/table-of-styles/table-of-styles-header >> src/table-of-styles.mdx
cat src/podium.css | sed 's/`//g' >> src/table-of-styles.mdx
cat src/table-of-styles/table-of-styles-footer >> src/table-of-styles.mdx
